remote_theme: pmarsceill/just-the-docs
logo: /assets/nrel.png
color_scheme: nrel
plugins:
    - jekyll-paginate
    - jekyll-feed
    - jekyll-remote-theme
    - jekyll-analytics

paginate: 3
paginate_path: /blog/page:num
baseurl: /HPC
search_enabled: true
title: NREL HPC github.io
collections:
    announcements:
        output: true

# google analytics setup using nrel.hpc.training@gmail.com
jekyll_analytics:
  GoogleAnalytics:
    id: UA-189117140-1
    anonymizeIp: false
